dataset: /content/heritage-index-of-economic-freedom-20250825135744.csv
features:
- property_rights
- government_integrity
- judicial_effectiveness
- tax_burden
- government_spending
- fiscal_health
- business_freedom
- labor_freedom
- trade_freedom
- investment_freedom
- financial_freedom
imputation_strategy: median_by_country
model_type: polynomial_regression
polynomial_degree: 2
regression_alpha: 1.0
split_year: 2020
target: overall_score_without_monetary_freedom
